name: release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build
        run: |
          GOOS=linux go build -ldflags "-w -s" -o release/GenerateAnimePage .
          chmod +x ./GenerateAnimePage
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/GenerateAnimePage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}